export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

//Types for Job
export const NEW_JOB_REQUEST = "NEW_JOB_REQUEST";
export const NEW_JOB_SUCCESS = "NEW_JOB_SUCCESS";
export const NEW_JOB_FAILED = "NEW_JOB_FAILED";

export const ADD_JOB_SKILL_REQUEST = "ADD_JOB_SKILL_REQUEST";
export const ADD_JOB_SKILL_SUCCESS = "ADD_JOB_SKILL_SUCCESS";
export const ADD_JOB_SKILL_FAILED = "ADD_JOB_SKILL_FAILED";

export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAILED = "GET_JOBS_FAILED";

export const USER_JOB_POST_REQUEST = "USER_JOB_POST_REQUEST";
export const USER_JOB_POST_SUCCESS = "USER_JOB_POST_SUCCESS";
export const USER_JOB_POST_FAILED = "USER_JOB_POST_FAILED";

export const USER_BY_JOB_ID_REQUEST = "USER_BY_JOB_ID_REQUEST";
export const USER_BY_JOB_ID_SUCCESS = "USER_BY_JOB_ID_SUCCESS";
export const USER_BY_JOB_ID_FAILED = "USER_BY_JOB_ID_FAILED";

export const GET_JOB_BY_ID = "GET_JOB_BY_ID";
export const GET_JOB_BY_ID_SUCCESS = "GET_JOB_BY_ID_SUCCESS";
export const GET_JOB_BY_ID_FAILED = "GET_JOB_BY_ID_FAILED";

export const GET_APPLICATION_BY_ID = "GET_APPLICATION_BY_ID";
export const GET_APPLICATION_BY_ID_SUCCESS = "GET_APPLICATION_BY_ID_SUCCESS";
export const GET_APPLICATION_BY_ID_FAILED = "GET_APPLICATION_BY_ID_FAILED";

export const GET_JOB_OTHER_BY_ID = "GET_JOB_OTHER_BY_ID";
export const GET_JOB_OTHER_BY_ID_SUCCESS = "GET_JOB_OTHER_BY_ID_SUCCESS";
export const GET_JOB_OTHER_BY_ID_FAILED = "GET_JOB_OTHER_BY_ID_FAILED";

export const GET_JOB_SKILL_BY_ID = "GET_JOB_SKILL_BY_ID";
export const GET_JOB_SKILL_BY_ID_SUCCESS = "GET_JOB_SKILL_BY_ID_SUCCESS";
export const GET_JOB_SKILL_BY_ID_FAILED = "GET_JOB_SKILL_BY_ID_FAILED";
